version: '3.5'

x-environment-vars: &environment-vars
  POSTGRES_HOST: postgres
  DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
  REDIS_URL: redis://redis:6379/0
  ADMIN_EMAIL: "@{ADMIN_EMAIL}"
  ADMIN_PASSWORD: "@{ADMIN_PASSWORD}"

x-defaults: &defaults
  image: eventyay/open-event-server
  restart: unless-stopped
  environment:
    <<: *environment-vars
  depends_on:
    - postgres
    - redis
  volumes:
    - ./static:/data/app/static

services:

  postgres:
    image: postgres:10-alpine
    container_name: opev-postgres
    restart: unless-stopped
    volumes:
      - pg:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

  redis:
    image: redis:3-alpine
    container_name: opev-redis
    restart: unless-stopped
    command: redis-server
    volumes:
      - rd:/var/lib/redis/data

  web:
    <<: *defaults
    container_name: opev-web
    ports:
      - 8080:8080

  celery:
    <<: *defaults
    container_name: opev-celery
    environment:
      <<: *environment-vars
      DEPLOYMENT: celery
      C_FORCE_ROOT: "true"

volumes:
    pg:
    rd:
