dry-run: null
hookfiles: ./tests/hook_main.py
language: python
server: python manage.py runserver
server-wait: 2
init: false
custom:
  apiaryApiKey: ''
names: false
only: []
reporter: apiary
output: []
header: []
sorted: false
method: []
loglevel: warning
path: []
hooks-worker-timeout: 15000
hooks-worker-connect-timeout: 10000
hooks-worker-connect-retry: 1000
hooks-worker-after-connect-wait: 100
hooks-worker-term-timeout: 10000
hooks-worker-term-retry: 1000
hooks-worker-handler-host: 127.0.0.1
hooks-worker-handler-port: 61321
config: ./dredd.yml
blueprint: docs/api/api_blueprint.apib
endpoint: 'http://localhost:5000'
